apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-java-app-pv
  labels:
    type: local
    app: my-java-app
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/my-java-app"
