apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-java-app-pvc
  labels:
    app: my-java-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
